Repository DCMLab/reductive_analysis_app, pull requests merged in 2021-04, with the labels that each got.

#72 List selected objects in semi-transparent notification which disappears as soon as it is cleared.
  css/style.css
  index.html
  js/main.js
Labels: enhancement, ui

#74 Added notes
  index.html
  js/coordinates.js
  js/main.js
  js/utils.js
Labels: enhancement

#80 Relation filters styling
  css/style.css
  js/ui.js
Labels: ui
